from typing import List, Dict

NIFTY_200_STOCKS: List[Dict[str, str]] = [
    {"name": "360 ONE WAM Ltd.", "symbol": "360ONE"},
    {"name": "ABB India Ltd.", "symbol": "ABB"},
    {"name": "APL Apollo Tubes Ltd.", "symbol": "APLAPOLLO"},
    {"name": "AU Small Finance Bank Ltd.", "symbol": "AUBANK"},
    {"name": "Adani Energy Solutions Ltd.", "symbol": "ADANIENSOL"},
    {"name": "Adani Enterprises Ltd.", "symbol": "ADANIENT"},
    {"name": "Adani Green Energy Ltd.", "symbol": "ADANIGREEN"},
    {"name": "Adani Ports and Special Economic Zone Ltd.", "symbol": "ADANIPORTS"},
    {"name": "Adani Power Ltd.", "symbol": "ADANIPOWER"},
    {"name": "Adani Total Gas Ltd.", "symbol": "ATGL"},
    {"name": "Aditya Birla Capital Ltd.", "symbol": "ABCAPITAL"},
    {"name": "Alkem Laboratories Ltd.", "symbol": "ALKEM"},
    {"name": "Ambuja Cements Ltd.", "symbol": "AMBUJACEM"},
    {"name": "Apollo Hospitals Enterprise Ltd.", "symbol": "APOLLOHOSP"},
    {"name": "Ashok Leyland Ltd.", "symbol": "ASHOKLEY"},
    {"name": "Asian Paints Ltd.", "symbol": "ASIANPAINT"},
    {"name": "Astral Ltd.", "symbol": "ASTRAL"},
    {"name": "Aurobindo Pharma Ltd.", "symbol": "AUROPHARMA"},
    {"name": "Avenue Supermarts Ltd.", "symbol": "DMART"},
    {"name": "Axis Bank Ltd.", "symbol": "AXISBANK"},
    {"name": "BSE Ltd.", "symbol": "BSE"},
    {"name": "Bajaj Auto Ltd.", "symbol": "BAJAJ-AUTO"},
    {"name": "Bajaj Finance Ltd.", "symbol": "BAJFINANCE"},
    {"name": "Bajaj Finserv Ltd.", "symbol": "BAJAJFINSV"},
    {"name": "Bajaj Holdings & Investment Ltd.", "symbol": "BAJAJHLDNG"},
    {"name": "Bank of Baroda", "symbol": "BANKBARODA"},
    {"name": "Bank of India", "symbol": "BANKINDIA"},
    {"name": "Bharat Dynamics Ltd.", "symbol": "BDL"},
    {"name": "Bharat Electronics Ltd.", "symbol": "BEL"},
    {"name": "Bharat Forge Ltd.", "symbol": "BHARATFORG"},
    {"name": "Bharat Heavy Electricals Ltd.", "symbol": "BHEL"},
    {"name": "Bharat Petroleum Corporation Ltd.", "symbol": "BPCL"},
    {"name": "Bharti Airtel Ltd.", "symbol": "BHARTIARTL"},
    {"name": "Billionbrains Garage Ventures Ltd.", "symbol": "GROWW"},
    {"name": "Biocon Ltd.", "symbol": "BIOCON"},
    {"name": "Blue Star Ltd.", "symbol": "BLUESTARCO"},
    {"name": "Bosch Ltd.", "symbol": "BOSCHLTD"},
    {"name": "Britannia Industries Ltd.", "symbol": "BRITANNIA"},
    {"name": "CG Power and Industrial Solutions Ltd.", "symbol": "CGPOWER"},
    {"name": "Canara Bank", "symbol": "CANBK"},
    {"name": "Cholamandalam Investment and Finance Company Ltd.", "symbol": "CHOLAFIN"},
    {"name": "Cipla Ltd.", "symbol": "CIPLA"},
    {"name": "Coal India Ltd.", "symbol": "COALINDIA"},
    {"name": "Cochin Shipyard Ltd.", "symbol": "COCHINSHIP"},
    {"name": "Coforge Ltd.", "symbol": "COFORGE"},
    {"name": "Colgate Palmolive (India) Ltd.", "symbol": "COLPAL"},
    {"name": "Container Corporation of India Ltd.", "symbol": "CONCOR"},
    {"name": "Coromandel International Ltd.", "symbol": "COROMANDEL"},
    {"name": "Cummins India Ltd.", "symbol": "CUMMINSIND"},
    {"name": "DLF Ltd.", "symbol": "DLF"},
    {"name": "Dabur India Ltd.", "symbol": "DABUR"},
    {"name": "Divi's Laboratories Ltd.", "symbol": "DIVISLAB"},
    {"name": "Dixon Technologies (India) Ltd.", "symbol": "DIXON"},
    {"name": "Dr. Reddy's Laboratories Ltd.", "symbol": "DRREDDY"},
    {"name": "Dummy Vedanta Ltd. 1", "symbol": "DUMMYVEDL1"},
    {"name": "Dummy Vedanta Ltd. 2", "symbol": "DUMMYVEDL2"},
    {"name": "Dummy Vedanta Ltd. 3", "symbol": "DUMMYVEDL3"},
    {"name": "Dummy Vedanta Ltd. 4", "symbol": "DUMMYVEDL4"},
    {"name": "Eicher Motors Ltd.", "symbol": "EICHERMOT"},
    {"name": "Eternal Ltd.", "symbol": "ETERNAL"},
    {"name": "Exide Industries Ltd.", "symbol": "EXIDEIND"},
    {"name": "FSN E-Commerce Ventures Ltd.", "symbol": "NYKAA"},
    {"name": "Federal Bank Ltd.", "symbol": "FEDERALBNK"},
    {"name": "Fortis Healthcare Ltd.", "symbol": "FORTIS"},
    {"name": "GAIL (India) Ltd.", "symbol": "GAIL"},
    {"name": "GE Vernova T&D India Ltd.", "symbol": "GVT&D"},
    {"name": "GMR Airports Ltd.", "symbol": "GMRAIRPORT"},
    {"name": "Glenmark Pharmaceuticals Ltd.", "symbol": "GLENMARK"},
    {"name": "Godfrey Phillips India Ltd.", "symbol": "GODFRYPHLP"},
    {"name": "Godrej Consumer Products Ltd.", "symbol": "GODREJCP"},
    {"name": "Godrej Properties Ltd.", "symbol": "GODREJPROP"},
    {"name": "Grasim Industries Ltd.", "symbol": "GRASIM"},
    {"name": "HCL Technologies Ltd.", "symbol": "HCLTECH"},
    {"name": "HDFC Asset Management Company Ltd.", "symbol": "HDFCAMC"},
    {"name": "HDFC Bank Ltd.", "symbol": "HDFCBANK"},
    {"name": "HDFC Life Insurance Company Ltd.", "symbol": "HDFCLIFE"},
    {"name": "Havells India Ltd.", "symbol": "HAVELLS"},
    {"name": "Hero MotoCorp Ltd.", "symbol": "HEROMOTOCO"},
    {"name": "Hindalco Industries Ltd.", "symbol": "HINDALCO"},
    {"name": "Hindustan Aeronautics Ltd.", "symbol": "HAL"},
    {"name": "Hindustan Petroleum Corporation Ltd.", "symbol": "HINDPETRO"},
    {"name": "Hindustan Unilever Ltd.", "symbol": "HINDUNILVR"},
    {"name": "Hindustan Zinc Ltd.", "symbol": "HINDZINC"},
    {"name": "Hitachi Energy India Ltd.", "symbol": "POWERINDIA"},
    {"name": "Housing & Urban Development Corporation Ltd.", "symbol": "HUDCO"},
    {"name": "Hyundai Motor India Ltd.", "symbol": "HYUNDAI"},
    {"name": "ICICI Bank Ltd.", "symbol": "ICICIBANK"},
    {"name": "ICICI Lombard General Insurance Company Ltd.", "symbol": "ICICIGI"},
    {"name": "ICICI Prudential Asset Management Company Ltd.", "symbol": "ICICIAMC"},
    {"name": "IDFC First Bank Ltd.", "symbol": "IDFCFIRSTB"},
    {"name": "ITC Ltd.", "symbol": "ITC"},
    {"name": "Indian Bank", "symbol": "INDIANB"},
    {"name": "Indian Hotels Co. Ltd.", "symbol": "INDHOTEL"},
    {"name": "Indian Oil Corporation Ltd.", "symbol": "IOC"},
    {"name": "Indian Railway Catering And Tourism Corporation Ltd.", "symbol": "IRCTC"},
    {"name": "Indian Railway Finance Corporation Ltd.", "symbol": "IRFC"},
    {"name": "Indian Renewable Energy Development Agency Ltd.", "symbol": "IREDA"},
    {"name": "Indus Towers Ltd.", "symbol": "INDUSTOWER"},
    {"name": "IndusInd Bank Ltd.", "symbol": "INDUSINDBK"},
    {"name": "Info Edge (India) Ltd.", "symbol": "NAUKRI"},
    {"name": "Infosys Ltd.", "symbol": "INFY"},
    {"name": "InterGlobe Aviation Ltd.", "symbol": "INDIGO"},
    {"name": "JSW Energy Ltd.", "symbol": "JSWENERGY"},
    {"name": "JSW Steel Ltd.", "symbol": "JSWSTEEL"},
    {"name": "Jindal Steel Ltd.", "symbol": "JINDALSTEL"},
    {"name": "Jio Financial Services Ltd.", "symbol": "JIOFIN"},
    {"name": "Jubilant Foodworks Ltd.", "symbol": "JUBLFOOD"},
    {"name": "KEI Industries Ltd.", "symbol": "KEI"},
    {"name": "KPIT Technologies Ltd.", "symbol": "KPITTECH"},
    {"name": "Kalyan Jewellers India Ltd.", "symbol": "KALYANKJIL"},
    {"name": "Kotak Mahindra Bank Ltd.", "symbol": "KOTAKBANK"},
    {"name": "L&T Finance Ltd.", "symbol": "LTF"},
    {"name": "LG Electronics India Ltd.", "symbol": "LGEINDIA"},
    {"name": "LIC Housing Finance Ltd.", "symbol": "LICHSGFIN"},
    {"name": "LTM Ltd.", "symbol": "LTM"},
    {"name": "Larsen & Toubro Ltd.", "symbol": "LT"},
    {"name": "Laurus Labs Ltd.", "symbol": "LAURUSLABS"},
    {"name": "Lenskart Solutions Ltd.", "symbol": "LENSKART"},
    {"name": "Lodha Developers Ltd.", "symbol": "LODHA"},
    {"name": "Lupin Ltd.", "symbol": "LUPIN"},
    {"name": "MRF Ltd.", "symbol": "MRF"},
    {"name": "Mahindra & Mahindra Financial Services Ltd.", "symbol": "M&MFIN"},
    {"name": "Mahindra & Mahindra Ltd.", "symbol": "M&M"},
    {"name": "Mankind Pharma Ltd.", "symbol": "MANKIND"},
    {"name": "Marico Ltd.", "symbol": "MARICO"},
    {"name": "Maruti Suzuki India Ltd.", "symbol": "MARUTI"},
    {"name": "Max Financial Services Ltd.", "symbol": "MFSL"},
    {"name": "Max Healthcare Institute Ltd.", "symbol": "MAXHEALTH"},
    {"name": "Mazagoan Dock Shipbuilders Ltd.", "symbol": "MAZDOCK"},
    {"name": "Motilal Oswal Financial Services Ltd.", "symbol": "MOTILALOFS"},
    {"name": "MphasiS Ltd.", "symbol": "MPHASIS"},
    {"name": "Multi Commodity Exchange of India Ltd.", "symbol": "MCX"},
    {"name": "Muthoot Finance Ltd.", "symbol": "MUTHOOTFIN"},
    {"name": "NHPC Ltd.", "symbol": "NHPC"},
    {"name": "NMDC Ltd.", "symbol": "NMDC"},
    {"name": "NTPC Ltd.", "symbol": "NTPC"},
    {"name": "National Aluminium Co. Ltd.", "symbol": "NATIONALUM"},
    {"name": "Nestle India Ltd.", "symbol": "NESTLEIND"},
    {"name": "Oberoi Realty Ltd.", "symbol": "OBEROIRLTY"},
    {"name": "Oil & Natural Gas Corporation Ltd.", "symbol": "ONGC"},
    {"name": "Oil India Ltd.", "symbol": "OIL"},
    {"name": "One 97 Communications Ltd.", "symbol": "PAYTM"},
    {"name": "Oracle Financial Services Software Ltd.", "symbol": "OFSS"},
    {"name": "PB Fintech Ltd.", "symbol": "POLICYBZR"},
    {"name": "PI Industries Ltd.", "symbol": "PIIND"},
    {"name": "Page Industries Ltd.", "symbol": "PAGEIND"},
    {"name": "Patanjali Foods Ltd.", "symbol": "PATANJALI"},
    {"name": "Persistent Systems Ltd.", "symbol": "PERSISTENT"},
    {"name": "Phoenix Mills Ltd.", "symbol": "PHOENIXLTD"},
    {"name": "Pidilite Industries Ltd.", "symbol": "PIDILITIND"},
    {"name": "Polycab India Ltd.", "symbol": "POLYCAB"},
    {"name": "Power Finance Corporation Ltd.", "symbol": "PFC"},
    {"name": "Power Grid Corporation of India Ltd.", "symbol": "POWERGRID"},
    {"name": "Premier Energies Ltd.", "symbol": "PREMIERENE"},
    {"name": "Prestige Estates Projects Ltd.", "symbol": "PRESTIGE"},
    {"name": "Punjab National Bank", "symbol": "PNB"},
    {"name": "REC Ltd.", "symbol": "RECLTD"},
    {"name": "Radico Khaitan Ltd", "symbol": "RADICO"},
    {"name": "Rail Vikas Nigam Ltd.", "symbol": "RVNL"},
    {"name": "Reliance Industries Ltd.", "symbol": "RELIANCE"},
    {"name": "SBI Cards and Payment Services Ltd.", "symbol": "SBICARD"},
    {"name": "SBI Life Insurance Company Ltd.", "symbol": "SBILIFE"},
    {"name": "SRF Ltd.", "symbol": "SRF"},
    {"name": "Samvardhana Motherson International Ltd.", "symbol": "MOTHERSON"},
    {"name": "Shree Cement Ltd.", "symbol": "SHREECEM"},
    {"name": "Shriram Finance Ltd.", "symbol": "SHRIRAMFIN"},
    {"name": "Siemens Energy India Ltd.", "symbol": "ENRIN"},
    {"name": "Siemens Ltd.", "symbol": "SIEMENS"},
    {"name": "Solar Industries India Ltd.", "symbol": "SOLARINDS"},
    {"name": "State Bank of India", "symbol": "SBIN"},
    {"name": "Steel Authority of India Ltd.", "symbol": "SAIL"},
    {"name": "Sun Pharmaceutical Industries Ltd.", "symbol": "SUNPHARMA"},
    {"name": "Supreme Industries Ltd.", "symbol": "SUPREMEIND"},
    {"name": "Suzlon Energy Ltd.", "symbol": "SUZLON"},
    {"name": "Swiggy Ltd.", "symbol": "SWIGGY"},
    {"name": "TVS Motor Company Ltd.", "symbol": "TVSMOTOR"},
    {"name": "Tata Capital Ltd.", "symbol": "TATACAP"},
    {"name": "Tata Communications Ltd.", "symbol": "TATACOMM"},
    {"name": "Tata Consultancy Services Ltd.", "symbol": "TCS"},
    {"name": "Tata Consumer Products Ltd.", "symbol": "TATACONSUM"},
    {"name": "Tata Elxsi Ltd.", "symbol": "TATAELXSI"},
    {"name": "Tata Investment Corporation Ltd.", "symbol": "TATAINVEST"},
    {"name": "Tata Motors Ltd.", "symbol": "TMCV"},
    {"name": "Tata Motors Passenger Vehicles Ltd.", "symbol": "TMPV"},
    {"name": "Tata Power Co. Ltd.", "symbol": "TATAPOWER"},
    {"name": "Tata Steel Ltd.", "symbol": "TATASTEEL"},
    {"name": "Tech Mahindra Ltd.", "symbol": "TECHM"},
    {"name": "Titan Company Ltd.", "symbol": "TITAN"},
    {"name": "Torrent Pharmaceuticals Ltd.", "symbol": "TORNTPHARM"},
    {"name": "Trent Ltd.", "symbol": "TRENT"},
    {"name": "Tube Investments of India Ltd.", "symbol": "TIINDIA"},
    {"name": "UPL Ltd.", "symbol": "UPL"},
    {"name": "UltraTech Cement Ltd.", "symbol": "ULTRACEMCO"},
    {"name": "Union Bank of India", "symbol": "UNIONBANK"},
    {"name": "United Spirits Ltd.", "symbol": "UNITDSPR"},
    {"name": "Varun Beverages Ltd.", "symbol": "VBL"},
    {"name": "Vedanta Ltd.", "symbol": "VEDL"},
    {"name": "Vishal Mega Mart Ltd.", "symbol": "VMM"},
    {"name": "Vodafone Idea Ltd.", "symbol": "IDEA"},
    {"name": "Voltas Ltd.", "symbol": "VOLTAS"},
    {"name": "Waaree Energies Ltd.", "symbol": "WAAREEENER"},
    {"name": "Wipro Ltd.", "symbol": "WIPRO"},
    {"name": "Yes Bank Ltd.", "symbol": "YESBANK"},
    {"name": "Zydus Lifesciences Ltd.", "symbol": "ZYDUSLIFE"},
]
